name: ai4life
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pytorch=2.2.1
  - scikit-learn=1.4.1
  - scipy=1.12.0
  - pytorch-cuda=11.8
  - torchvision=0.17.1
  - transformers=4.38.1
  - libtiff=4.5.1
  - pip
  - pip:
      - accelerate==0.27.2
      - decord==0.6.0
      - evaluate==0.4.1
      - git+https://github.com/facebookresearch/pytorchvideo.git@main
      - wandb==0.16.3
